# Generated by Django 4.2.5 on 2025-04-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Име и фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Имейл')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес за доставка')),
                ('consent_to_privacy_policy', models.BooleanField(default=False, verbose_name='Съгласие с политиката за поверителност')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на поръчката')),
            ],
        ),
    ]
